spring.application.name=BookingSystem
server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/experts_db
spring.datasource.username=exp_user
spring.datasource.password=@@1223334444
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.application.admin.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/index.html
